src/getfilecontents.c, src/helpers.c, src/libeconf.c
Refactor the functions associated with reading content from files.
Replace `snprintf` with `strdup` and adapt the functions to the
features introduced in PR:#5.
=> Refactor getfilecontent functions

include/libeconf.h
Don't define our own errno, could break multi-threading
=> don't define our own errno

src/getfilecontents.c
Since the regex in `get_key_file()` function doesn't work properly
it is remove for now.
If you want multiple different chars as a delimiter just type them
in sequence, e.g. " \t" for both space and tab.
Note: Multiple char delimiters are not supported that way, but they
weren't before.
A proper way to handle delimiters needs to be added in future.
Fixes: #9
=> Remove regex, replace with strchr(delim, ch)

src/libeconf.c
`*default_dirs++` in src/libeconf.c throws a compiler warning,
since it can cause undefined behaviour, thus it's changed to
`default_dirs++`, which is what's wanted here.
=> Fix pointer arithmetic

src/mergefiles.c
Searching through XDG dirs should be enabled/disabled via a
`econf_set_opt()` function. Until it is implemented the XDG
feature is disabled.
=> Disable searching through XDG dirs for now

src/libeconf.c
Change error return value from empty string to NULL.
=> setStringValue return NULL on error/key not found

src/helpers.c
The closing bracket was not appended at the end as intended.
=> Fix addbrackets function

src/keyfile.c, tests/Makefile.am
Make `tst-setgetvalues1` pass.
Remove `XFAIL` for `tst-setgetvalues1`
=> Fix floating point number representation

src/getfilecontents.c
Make ch type int instead of size_t.
=> Fix size_t as return value of getc()

include/libeconf.h, lib/libeconf.map
econf_newIniFile, econf_newKeyFile, econf_writeFile are
not stable yet.
=> Make clear that the API and ABI of the three functions

.gitignore, tests/Makefile.am, tests/tst-logindefs2-data/logindefs.data, tests/tst-logindefs2.c
This test is currently failing due to some deficits of our parser (like handling empty keys as groups).
=> Add test case for reading login.defs with data from util-linux testsuite

src/keyfile.c
do that in the getBoolValueNum function, too.
=> Bool values read from a config file are not sanitzied, so we need to

include/libeconf.h, lib/Makefile.am, lib/libeconf.map, src/get_value_def.c
=> Implement econf_get*ValueDef functions: if key is not found, a provided

Makefile.am
This is required for packaging libeconf in Fedora.
=> Ensure LICENSE, README, and TODO are included in the release tarball

lib/libeconf.c
To resolve #110 , tested locally with reproduction case, no other use-after-free case found (at least none using the econf_free function)
=> Reset *key_file to NULL after free

meson.build
Are you interested in meson for this project? As one can see, it's way simpler than automake.
Thanks to the `libeconf_dep` variable in meson, it would be super easy for devs to add libeconf as a subproject.
=> add support for meson

example/example.c, tests/tst-groups2.c, tests/tst-groups3.c, tests/tst-logindefs1.c, tests/tst-logindefs2.c
Fixing the various i586 issues found in staging as a result of moving to meson
Failure: https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:B/libeconf/standard/i586
Working example from these changes: https://build.opensuse.org/package/live_build_log/home:RBrownSUSE:branches:devel:kubic/libeconf/openSUSE_Tumbleweed/i586
=> Fix build on i586

include/libeconf.h
The C ABI marker section for C++ compilers should not
include the standard headers as we are only need this
for our API, not the standard library.
=> Move C++ ABI compatibility section

README.md
The debian package linter spotted this typo (in the package description
which was copied from the initial part of the README):
W: libeconf-dev: spelling-error-in-description serveral several
N:
N:    Lintian found a spelling error in the package description. Lintian has a
N:    list of common misspellings that it looks for. It does not have a
N:    dictionary like a spelling checker does. It is particularly picky about
N:    spelling and capitalization in package descriptions since they're very
N:    visible to end users.
N:
N:    Severity: warning
N:
N:    Check: fields/description
=> Fix typo in README.md: serveral -> several

README.md
This will fix two typos and corrects the Markdown, which will satisfy Markdown linters.
=> Fix typo and Markdown in README.md

lib/helpers.c, lib/libeconf.c
Fixes for several covscan issues:
Error: RESOURCE_LEAK (CWE-772): [#def1]
libeconf-0.3.8/lib/libeconf.c:205: alloc_arg: "econf_readFile" allocates memory that is stored into "key_file".
libeconf-0.3.8/lib/libeconf.c:237: leaked_storage: Variable "key_file" going out of scope leaks the storage it points to.
235|     key_files = calloc((++size), sizeof(econf_file*));
236|     if (key_files == NULL)
237|->     return ECONF_NOMEM;
238|
239|     if (size == 2)
Error: RESOURCE_LEAK (CWE-772): [#def2]
libeconf-0.3.8/lib/libeconf.c:297: alloc_fn: Storage is returned from allocation function "combine_strings".
libeconf-0.3.8/lib/libeconf.c:297: var_assign: Assigning: "save_to" = storage returned from "combine_strings(save_to_dir, file_name, '/')".
libeconf-0.3.8/lib/libeconf.c:301: noescape: …
=> Covscan issues

lib/getfilecontents.c
Valgrind found a memory leak when calling
econf_file *kf;
econf_readFile(&kf, "test.ini", "=", "#");
econf_freeFile(kf);
This is caused by the global variable last_scanned_filename which is
assigned dynamically and thus won't be free'd on exit.
Just use fixed size array instead.
Also declare the global variables as static while at it.
=> Allocate fixed length filename buffer

include/libeconf.h
required for mode_t, gid_t, uid_t
=> libeconf.h: add missing sys/types.h header

lib/libeconf.c
The function `econf_readDirsHistoryWithCallback` leaks memory if no file is found.
If libeconf is compiled with address sanitizer, you can reproduce this with `econftool` by calling it with non-existing files, e.g. `econftool show non.existing`.
=> Plug memory leak

lib/getfilecontents.c
Mentioned below as well: This is a purely defensive measure. NO real bug exists!
If a file ends with a double quote character (") without a newline and this double quote is interpreted as start of data, then an access after the last NUL byte which was written by fgets could happen.
This happens because data, after *data == '"' is true, is incremented. It would point to the NUL byte. Since strlen(data) is 0, the pointer p will point at data, i.e. fgets' NUL byte. The next while loops won't apply, because p is not larger than data.
The if-block itself leads to a decrement of data (correct). But after that, "p + 1" is checked. This access goes beyond the NUL byte of fgets, since "p" itself already points to that NUL byte.
Since fgets won't write into the complete array, this is currently no …
=> Improve data quote check in read_file

lib/libeconf_ext.c, lib/readconfig.c
```
Error: RESOURCE_LEAK (CWE-772):
libeconf-0.4.1/util/econftool.c:185: alloc_arg: "econf_getExtValue" allocates memory that is stored into "value".
libeconf-0.4.1/util/econftool.c:189: leaked_storage: Variable "value" going out of scope leaks the storage it points to.
187| fprintf(stderr, "%d: %s\n", econf_error, econf_errString(econf_error));
188| econf_free(keys);
189|-> return econf_error;
190| }
191| if (value != NULL) {
```
```
Error: RESOURCE_LEAK (CWE-772):
libeconf-0.4.1/lib/libeconf.c:312: alloc_arg: "econf_readDirsHistory" allocates memory that is stored into "key_files".
libeconf-0.4.1/lib/libeconf.c:321: leaked_storage: Variable "key_files" going out of scope leaks the storage it points to.
319| comment);
320| if (error != ECONF_SUCCESS)
321|-> return error;
322|
323| // …
```
=> Fix static analyzer detected issues

lib/libeconf.c
PATH_MAX is defined in limits.h in POSIX.
Fixes https://github.com/openSUSE/libeconf/issues/197
ref: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/limits.h.html
=> Fix build with musl libc on ppc64le

tests/meson.build, tests/tst-comments2-data/env.conf, tests/tst-comments2.c
The comment character (e.g. '#') in a quoted string should not be handled as comment but as part of the value.
See https://github.com/linux-pam/linux-pam/issues/13
=> tst-comments2: comment sign in quoted string

lib/helpers.c, lib/keyfile.c, lib/keyfile.h, lib/libeconf.c
I've put both commits into one pull request, since both technically reduce the accessible interface exposed through libeconf.
- The functions `clearblank` and `setComments` can be removed
- Avoid exposing two global variables, instead turn them into `static` ones
=> Remove unused functions and reduce variable visibility

lib/econf_error.c
The snprintf function guarantees NUL-termination. No need to handle it manually.
=> Simplify snprintf call

meson.build
The correct way to build a static library with meson is to use the `-Ddefault_library=both` or `-Ddefault_library=static` meson configure arguments.
=> Remove static library declaration from meson

lib/CMakeLists.txt, lib/libeconf.map, meson.build
Resolves the following lld link errors/warnings:
```
ld.lld: error: version script assignment of 'LIBECONF_0.3' to symbol 'econf_getGroupsDef' failed: symbol not defined
ld.lld: error: version script assignment of 'LIBECONF_0.3' to symbol 'econf_getKeysDef' failed: symbol not defined
ld.lld: warning: attempt to reassign symbol 'econf_readFileWithCallback' of version 'LIBECONF_0.4' to version 'LIBECONF_0.5'
ld.lld: warning: attempt to reassign symbol 'econf_readDirsWithCallback' of version 'LIBECONF_0.4' to version 'LIBECONF_0.5'
ld.lld: warning: attempt to reassign symbol 'econf_readDirsHistoryWithCallback' of version 'LIBECONF_0.4' to version 'LIBECONF_0.5'
```
Also add linker flags to prevent future errors/warnings from making it into the code base.
=> Remove undefined symbols from version script

cmake/libeconf.pc.in, lib/CMakeLists.txt
Per <https://cmake.org/cmake/help/v4.1/module/GNUInstallDirs.html> `CMAKE_INSTALL_<dir>` variables can be absolute. In this case they should not be appended to the prefix in the generated `.pc` file.
=> cmake: Fix .pc file with absolute CMAKE_INSTALL_<dir>
